language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
      - UO237104@uniovi.es
      - uo240772@uniovi.es
      - uo239995@uniovi.es
    on_success: change
    on_failure: always
  before_script:
  - pip install --user codecov

after_success:
  - codecov
